# Build configuration
[build]
  # The command to build your project
  command = "npm run build"
  # The directory to output the build artifacts
  publish = "build"
  # The base directory for the build
  base = "/"

# Environment variables
[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  # NPM version
  NPM_VERSION = "10"

# Production environment specific settings
[env.production]
  # Caching headers for production
  CACHE_CONTROL = "public, max-age=86400"
  
  # Custom headers for production
  [env.production.headers]
    [env.production.headers."/*"]
      "X-Frame-Options" = "DENY"
      "X-XSS-Protection" = "1; mode=block"
      "X-Content-Type-Options" = "nosniff"
      "Referrer-Policy" = "strict-origin-when-cross-origin"
      "Strict-Transport-Security" = "max-age=31536000; includeSubDomains; preload"

# Staging environment specific settings
[env.staging]
  # Cache control headers for staging
  CACHE_CONTROL = "public, max-age=3600"

# Routing for SPA
[[routes]]
  pattern = "/*"
  script = ""
  dest = "/index.html"
  status = 200

# Asset caching rules
[[routes]]
  pattern = "/*.js"
  script = ""
  dest = "/$1.js"
  [routes.headers]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[routes]]
  pattern = "/*.css"
  script = ""
  dest = "/$1.css"
  [routes.headers]
    "Cache-Control" = "public, max-age=31536000, immutable"

[[routes]]
  pattern = "/assets/*"
  script = ""
  dest = "/assets/$1"
  [routes.headers]
    "Cache-Control" = "public, max-age=31536000, immutable"

# Optimization settings
[optimization]
  compress = true
  minify_css = true
  minify_js = true 